# Generated by Django 5.2.3 on 2025-08-15 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(help_text='Usuarios que pueden gestionar esta empresa', related_name='empresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asociados'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la empresa/compañía'),
        ),
    ]
