# Generated by Django 5.2.3 on 2025-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_empresa_usuario_empresa_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechas_faltas_injustificadas',
            field=models.JSONField(blank=True, default=list, help_text='Formato YYYY-MM-DD', verbose_name='Fechas de Faltas Injustificadas'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fechas_faltas_justificadas',
            field=models.JSONField(blank=True, default=list, help_text='Formato YYYY-MM-DD', verbose_name='Fechas de Faltas Justificadas'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechas_faltas',
            field=models.JSONField(blank=True, default=list, help_text='Formato YYYY-MM-DD - En proceso de migración', verbose_name='Fechas de Faltas (Compatibilidad)'),
        ),
    ]
