# Generated by Django 3.2 on 2024-01-15 00:00

from django.db import migrations

def migrate_existing_absences(apps, schema_editor):
    Empleado = apps.get_model('gestion', 'Empleado')
    
    for empleado in Empleado.objects.all():
        # Migrar faltas existentes a injustificadas (comportamiento anterior)
        if hasattr(empleado, 'fechas_faltas') and empleado.fechas_faltas:
            empleado.fechas_faltas_injustificadas = empleado.fechas_faltas
            empleado.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_empleado_fechas_faltas_injustificadas_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_absences),
    ]