# Generated by Django 5.2.3 on 2025-06-14 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_user_tipo_usuario_empresa_empleado_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dias_descanso',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]), blank=True, default=list, size=None),
        ),
    ]
