# Generated by Django 5.2.3 on 2025-09-03 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_migrate_existing_absences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='RFC inválido para persona física. Formato requerido: 4 letras + 6 dígitos + 3 caracteres alfanuméricos', regex='^[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3}$')], verbose_name='RFC'),
        ),
    ]
