# Generated by Django 5.2.3 on 2025-06-15 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_empleado_dias_descanso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.CharField(help_text='Formato: DD/MM/YYYY', max_length=10, validators=[django.core.validators.RegexValidator(message='La fecha debe tener formato DD/MM/YYYY', regex='^\\d{2}/\\d{2}/\\d{4}$')]),
        ),
    ]
