# Generated by Django 5.2.3 on 2025-06-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_empleado_options_alter_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
