# Generated by Django 5.2.3 on 2025-06-25 02:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_empleado_apellido_materno_empleado_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('gestionar_nomina', 'Puede gestionar nómina de la empresa')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='empresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asociados'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nss',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El NSS debe tener 11 dígitos', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC no tiene un formato válido para persona física', regex='^[A-Z&Ñ]{4}\\d{6}[A-V1-9][0-9A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC no tiene un formato válido', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-V1-9][0-9A-Z]$')]),
        ),
    ]
