# Generated by Django 5.2.3 on 2025-06-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_empleado_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='rfc',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
