# Generated by Django 5.2.3 on 2025-07-02 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_empresa_rfc_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='periodo_nominal',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=10, verbose_name='Periodo Nominal'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together={('empleado', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
