# Generated by Django 5.2.3 on 2025-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_empleado_periodo_nominal_nomina_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
            },
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dias_descanso',
        ),
        migrations.AddField(
            model_name='empleado',
            name='faltas',
            field=models.ManyToManyField(blank=True, to='gestion.falta'),
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='calculos',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='dias_festivos',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='dias_trabajados',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='salario_neto',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='tipo_nomina',
        ),
    ]
