# Generated by Django 5.2.3 on 2025-07-04 05:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_falta_alter_nomina_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='faltas',
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('gestionar_nominas', 'Puede gestionar nóminas de la empresa')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='regimen_fiscal',
        ),
        migrations.AddField(
            model_name='empleado',
            name='dias_descanso',
            field=models.JSONField(default=list, help_text='Días de descanso del empleado (0=Lunes, 6=Domingo)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dias_trabajados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días trabajados en el periodo actual (calculado automáticamente)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='faltas_en_periodo',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días faltados en el periodo actual', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='calculos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nomina',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='gestion.empresa'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=10),
        ),
        migrations.AddField(
            model_name='nomina',
            name='faltas_en_periodo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='salario_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_nomina',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (7 días)'), ('QUINCENAL', 'Quincenal (variable días)'), ('MENSUAL', 'Mensual (variable días)')], default='QUINCENAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre completo de la empresa', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together={('empleado', 'fecha_inicio', 'fecha_fin')},
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido_paterno', 'apellido_materno', 'empresa'), name='unique_empleado_empresa'),
        ),
        migrations.DeleteModel(
            name='Falta',
        ),
    ]
