# Generated by Django 5.2.3 on 2025-07-04 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_empleado_faltas_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
