# Generated by Django 5.2.3 on 2025-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_empresa_options_alter_empresa_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechas_faltas',
            field=models.JSONField(default=list, help_text='Fechas específicas de faltas en formato YYYY-MM-DD'),
        ),
    ]
