# Generated by Django 5.2.3 on 2025-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_empleado_fechas_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
