# Generated by Django 5.2.3 on 2025-07-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_nomina_dias_trabajados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='dias_trabajados',
        ),
    ]
