# Generated by Django 5.2.3 on 2025-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_remove_nomina_dias_trabajados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechas_faltas',
            field=models.JSONField(blank=True, default=list, help_text='Fechas específicas de faltas en formato YYYY-MM-DD'),
        ),
    ]
