# Generated by Django 5.2.3 on 2025-07-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_empleado_fechas_faltas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='dias_trabajados',
            new_name='dias_laborados',
        ),
    ]
