# Generated by Django 5.2.3 on 2025-07-08 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_rename_dias_trabajados_empleado_dias_laborados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
