# Generated by Django 5.2.3 on 2025-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_empresa_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='zona_salarial',
            field=models.CharField(choices=[('general', 'Zona General'), ('frontera', 'Zona Frontera Norte')], default='general', max_length=10, verbose_name='Zona Salarial'),
        ),
    ]
