# Generated by Django 5.2.3 on 2025-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_empleado_zona_salarial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='periodo_nominal',
            field=models.CharField(blank=True, help_text='Identificador del periodo nominal (ej. ENERO/01)', max_length=20, null=True),
        ),
    ]
