# Generated by Django 5.2.3 on 2025-07-21 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_nomina_periodo_nominal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='salario_diario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo Mensual'),
        ),
    ]
