# Generated by Django 5.2.3 on 2025-07-21 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remove_empleado_salario_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salario diario del empleado para cálculo de nóminas semanales/quincenales', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Diario'),
        ),
    ]
