# Generated by Django 5.2.3 on 2025-07-22 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_empleado_salario_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Diario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo Mensual'),
        ),
    ]
