# Generated by Django 5.2.3 on 2025-07-23 00:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_empleado_salario_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='gestion.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nss',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El NSS debe tener 11 dígitos', regex='^\\d{11}$')], verbose_name='Número de Seguro Social'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='periodo_nominal',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=10, verbose_name='Periodo de Pago'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC no tiene un formato válido para persona física', regex='^[A-Z&Ñ]{4}\\d{6}[A-V1-9][0-9A-Z]$')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio para periodos SEMANAL/QUINCENAL', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Diario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio EXCLUSIVAMENTE para periodo MENSUAL', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo Mensual'),
        ),
    ]
