# Generated by Django 5.2.3 on 2025-07-23 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_empleado_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='periodo_nominal',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=10, verbose_name='Periodo Nominal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Diario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo Mensual'),
        ),
    ]
