# Generated by Django 5.2.3 on 2025-07-23 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_empleado_activo_alter_empleado_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dias_descanso',
            field=models.JSONField(default=list, help_text='Días de descanso del empleado (0=Lunes, 6=Domingo)', verbose_name='Días de Descanso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dias_laborados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días trabajados en el periodo actual', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días Laborados'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='faltas_en_periodo',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días faltados en el periodo actual', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Faltas en Periodo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechas_faltas',
            field=models.JSONField(blank=True, default=list, help_text='Fechas específicas de faltas en formato YYYY-MM-DD', verbose_name='Fechas de Faltas'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='periodo_nominal',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=10, verbose_name='Periodo de Pago'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='RFC inválido para persona física', regex='^[A-Z&Ñ]{4}\\d{6}[A-V1-9][0-9A-Z]$')], verbose_name='RFC'),
        ),
    ]
