# Generated by Django 5.2.3 on 2025-07-23 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_empleado_activo_alter_empleado_dias_descanso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dias_descanso',
            field=models.JSONField(default=list, help_text='Días de descanso (0=Lunes, 6=Domingo)', verbose_name='Días de Descanso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dias_laborados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Calculado automáticamente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días Laborados'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='faltas_en_periodo',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Faltas en Periodo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechas_faltas',
            field=models.JSONField(blank=True, default=list, help_text='Formato YYYY-MM-DD', verbose_name='Fechas de Faltas'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio para periodos SEMANAL/QUINCENAL', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Diario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio solo para periodo MENSUAL', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo Mensual'),
        ),
    ]
