# Generated by Django 5.2.3 on 2025-07-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_alter_empleado_dias_descanso_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('rfc', 'empresa'), name='unique_rfc_empresa', violation_error_message='No se pueden registrar dos empleados activos con el mismo RFC en la misma empresa'),
        ),
    ]
