# Generated by Django 5.2.3 on 2025-07-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_empleado_unique_rfc_empresa'),
    ]

    operations = [
    ]
