# Generated by Django 5.2.3 on 2025-07-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20250728_1906'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['empleado', 'fecha_inicio'], name='gestion_nom_emplead_8fe78d_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['estado'], name='gestion_nom_estado_10f1a8_idx'),
        ),
    ]
